doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        driver: pdo_sqlite
        logging: true

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            DoctrineQuery:
                dir: 'Entity'
                is_bundle: true
            Fundamental:
                dir: 'Entity'
                is_bundle: true
            SecurityAuth:
                dir: 'Entity'
                is_bundle: true
        #     App:
        #         is_bundle: false
        #         type: annotation
        #         dir: '%kernel.project_dir%/src/Entity'
        #         prefix: 'App\Entity'
        #         alias: App
