#framework:
    # mailer:
    #     dsn: '%env(MAILER_DSN)%'
    #     envelope:
    #         sender: "%env(string:default:default_admin_email:ADMIN_EMAIL)%"

    # routing:
    #         # Route your messages to the transports
    #         App\Message\CommentMessage: async
    #         Symfony\Component\Mailer\Messenger\SendEmailMessage: async
