doctrine:
    dbal:
        #url: '%env(resolve:DATABASE_URL)%'
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_MYSQL_URL)%'
                driver: pdo_mysql
                #dbname:           Symfony
                #user:             root
                #password:         null
                #host:             localhost
                server_version:   '5.6'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                mapping_types:
                    enum: string

            postgres:
                url: '%env(resolve:DATABASE_POSTGRES_URL)%'
                #dbname:           customer
                #user:             root
                #password:         null
                #host:             localhost
                server_version:   '5.7'
