services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    SecurityAuth\:
        resource: '../../'
        exclude:
            - '../Tests/'

    SecurityAuth\Controller\:
        resource: '../../Controller/'
        tags: ['controller.service_arguments']