services:
    # _defaults:
    #     autowire: true      # DON'T FORGET TO USE IT INSIDE BUNDLES TOO.
    #     autoconfigure: true

    DoctrineQuery\:
        autowire: true # todo: manually configure
        autoconfigure: true
        resource: '../../'
            
    DoctrineQuery\Controller\:
        autowire: true 
        autoconfigure: true
        resource: '../../Controller/'

        # Not used, keep for legacy!
        #tags: ['container.service_subscriber']
        # calls:
        #     - method: setContainer
        #       arguments: ['@service_container']

    # Not used anymore, keep for legacy!
    # DoctrineQuery\Repository\CategoryRepository:
    #     autowire: true
    #     tags: ['doctrine.repository_service']
    before_request_listener:
        class: DoctrineQuery\EventListener\BeforeRequestListener
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            -
                name: kernel.event_listener
                event: kernel.request
                method: onKernelRequest
